services:
 
  mysql:
    image: mysql:5.7
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: admin 
      MYSQL_USER: user_p
      MYSQL_PASSWORD: user_password
    volumes:  
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

  php:
    build: .
    container_name: php_app
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    networks:
      - my_network

volumes:
  mysql_data:

networks:
  my_network: